# Site settings
title: "~/fxcosta"

# Default header image
header_img:
  url: "assets/img/home-bg.jpg"

comments:
  enabled: true
  disqus_shortname: ""

social_networks:
    twitter: "fxcosta" # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: "https://github.com/fxcosta"
    dribbble: # Your id
    linkedin: # Your URL
    email: fx3costa@gmail.com

# Forms
forms:
    contact:
        getsimpleform_api_token: 
